title: TIL
author: Danny O'Brien <danny@spesh.com>
theme: jekyll-theme-modernist

collections:
  tils:
    output: true
    permalink: /:collection/:name

social-network-links:
  email: "danny@spesh.com"
  rss: true  
