title: Danny O'Brien's TIL
author: Danny O'Brien <danny@spesh.com>
theme: jekyll-theme-modernist

collections:
  tils:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "tils"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

social-network-links:
  email: "danny@spesh.com"
  rss: true  
